In [1]:
import numpy as np

In [2]:
url="https://s3-api.us-geo.objectstorage.softlayer.net/cf-courses-data/CognitiveClass/DA0101EN/coursera/project/kc_house_data_NaN.csv"

In [3]:
#loading data
house=np.genfromtxt(url, delimiter=',',skip_footer=1)
house[0:5,:]

array([[            nan,             nan,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan,
                    nan,             nan,             nan,
                    nan],
       [ 0.00000000e+00,  7.12930052e+09,             nan,
         2.21900000e+05,  3.00000000e+00,  1.00000000e+00,
         1.18000000e+03,  5.65000000e+03,  1.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  3.00000000e+00,
         7.00000000e+00,  1.18000000e+03,  0.00000000e+00,
         1.95500000e+03,  0.00000000e+00,  9.81780000e+04,
         4.75112000e+01, -1.22257000e+02,  1.34000000e+03,
         5.65000000e+03],
       [ 1.00000000e+00,  6.41410019e+09,             nan,
         5.38000000e+05,  3.00000000e+00,  2.25000000e+00,
    

In [4]:
house.shape

(21613, 22)

1stcolumn contains nan value and 2nd column contains house id and 3rd colum contains sellling date. and 1st row conatins name of the columns.

In [5]:
#removing 1st,2nd and 3rd columns and 1st row
house = house[1:, 3:]

In [6]:
house.shape

(21612, 19)

## checking and removing NaN values

In [7]:
#checking for nan values
np.isnan(np.sum(house))

True

In [8]:
#position of the NaN values
nan_index = np.where(np.isnan(house))
print(nan_index)

(array([  875,   875,  1149,  3119,  3119,  3467,  4868,  5832,  6994,
        6994,  8477,  8484,  9773,  9773,  9854,  9854, 10481, 12653,
       14423, 14423, 18379, 19452, 19452]), array([1, 2, 2, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1,
       2]))


In [9]:
#droping all the NaN values
mask = np.array([~np.any(np.isnan(row)) for row in house])
house = house[mask]

In [10]:
#checking for nan values
np.isnan(np.sum(house))

False

In [11]:
house.shape

(21596, 19)

## Categorizing dataset depending on number of bedrooms

In [264]:
#number of bedroom column
house[:,1]

array([3., 3., 2., ..., 4., 2., 3.])

In [265]:
#minumum number of bedroom
minn=np.min(house[:,1])
minn

1.0

In [266]:
#maximum number of bedroom
maxx=np.max(house[:,1])
maxx

33.0

In [267]:
house_copy=np.copy(house)

In [268]:
#replacing values with mall_apartment, medium_apartment and big_apartment
house_bed= np.digitize(house_copy[:,1],bins=[3,5,10])

In [269]:
label= {0: 'small_apartment', 1: 'medium_apartment', 2: 'big_apartment', 3: 'Extra_large_apartment'}
house_bed= [label[j] for j in house_bed]

In [270]:
unique, counts = np.unique(house_bed, return_counts=True)
dict(zip(unique, counts))
print("number of small apartment is : "+ str(counts[3]))
print("number of medium apartment is : "+ str(counts[2]))
print("number of big apartment is : "+ str(counts[1]))
print("number of Extra large apartment is : "+ str(counts[0]))

number of small apartment is : 2955
number of medium apartment is : 16706
number of big apartment is : 1930
number of Extra large apartment is : 5


Apartments haveing 3-4 bedrooms are the most common apartments in the king county.

## Pricing in depth of housing in King Country

In [271]:
#price column
house[:10,0].tolist()

[221900.0,
 538000.0,
 180000.0,
 604000.0,
 510000.0,
 1225000.0,
 257500.0,
 291850.0,
 229500.0,
 323000.0]

In [272]:
#The most common price
vals, counts = np.unique(house[:,0], return_counts=True)
#print(vals,counts)
print("The most common price for a house is : $"+ str(vals[np.argmax(counts)]))

The most common price for a house is : $350000.0


In [273]:
#counting min,max,median and mean
mean=np.mean(house[:,0])
print("mean price is: $"+str(mean))
median=np.median(house[:,0])
print("median price is: $"+str(median))
print()
std=np.std(house[:,0])
print("price range of the houses are $"+ str(np.min(house[:,0])) +" to $"+ str(np.max(house[:,0])))

mean price is: $540212.8847008705
median price is: $450000.0

price range of the houses are $78000.0 to $7700000.0


In [274]:
skew=(3*(mean-median))/std
print("Skewness is "+ str(skew))

Skewness is 0.7371722737737209


Since the skewness is positive, if we draw the distribution curve of "Price" column, we will have Positive or right screw distribution. This means that, most of the outliers occur on the right side of the graph meaning <i>for bigger price we have more outliers.</i>

## relationship between price and different features

In [275]:
#xaxis,yaxis
#correlation between no of bedrooms and price
correlation=np.corrcoef(house[:,1], house[:,0])
correlation

array([[1.        , 0.30877185],
       [0.30877185, 1.        ]])

In [276]:
#correlation between no of bathrooms and price
correlation2=np.corrcoef(house[:,2], house[:,0])
correlation2

array([[1.        , 0.52589939],
       [0.52589939, 1.        ]])

In [277]:
#correlation between square foot living and price
correlation3=np.corrcoef(house[:,3], house[:,0])
correlation3

array([[1.        , 0.70190519],
       [0.70190519, 1.        ]])

In [278]:
#correlation between year build and price
correlation4=np.corrcoef(house[:,12], house[:,0])
correlation4

array([[1.        , 0.05402024],
       [0.05402024, 1.        ]])

In [279]:
#correlation between floor number and price
correlation5=np.corrcoef(house[:,5], house[:,0])
correlation5

array([[1.        , 0.25684656],
       [0.25684656, 1.        ]])

In [280]:
#correlation between zip code and price
correlation6=np.corrcoef(house[:,14], house[:,0])
correlation6

array([[ 1.        , -0.05340587],
       [-0.05340587,  1.        ]])

The price is most strongly correlated with the size of the house than any other feature and least correlated with the year the house was built. Price also varies more strongly with the number of bathrooms than the number of bedrooms. zip code has negative corelation with price meaning the further we go from the center the lower the price of house goes.

## how price changes with water front view

In [281]:
price=house[:,0]
water=house[:,6]

In [282]:
[[group_val, price[water==group_val].mean()] for group_val in np.unique(water)]

[[0.0, 531682.5300237951], [1.0, 1661876.0245398772]]

In [283]:
price_difference=price[1]-price[0]
price_difference

316100.0

On average, house with water front views are more expenssive than with out water front views and the average difference is $316,100.

## Relationship between price and decade when the house was build

In [348]:
house_copy=np.copy(house)

In [351]:
house_yr= np.digitize(house_copy[:,12],bins=[1950,2000])
house_yr

array([1, 1, 0, ..., 2, 2, 2])

In [352]:
label= {0: 'early 1900s', 1: 'late 1900s', 2: 'early 2000s'}
house_yr= [label[j] for j in house_yr]


In [353]:
np.shape(house_yr)

(21596,)

In [354]:
house_yr=np.reshape(house_yr, (21596,1))

In [355]:
np.shape(house_yr)

(21596, 1)

In [356]:
house_copy=np.hstack([house_copy,house_yr])

In [357]:
house_copy


array([['221900.0', '3.0', '1.0', ..., '1340.0', '5650.0', 'late 1900s'],
       ['538000.0', '3.0', '2.25', ..., '1690.0', '7639.0', 'late 1900s'],
       ['180000.0', '2.0', '1.0', ..., '2720.0', '8062.0', 'early 1900s'],
       ...,
       ['400000.0', '4.0', '2.5', ..., '1830.0', '7200.0', 'early 2000s'],
       ['402101.0', '2.0', '0.75', ..., '1020.0', '2007.0',
        'early 2000s'],
       ['400000.0', '3.0', '2.5', ..., '1410.0', '1287.0', 'early 2000s']],
      dtype='<U32')

In [358]:
price=house_copy[:,0]
year=house_copy[:,-1]

In [362]:
price=price.astype(np.float)

In [363]:
[[group_val, price[year==group_val].mean()] for group_val in np.unique(year)]

[['early 1900s', 546684.6141843972],
 ['early 2000s', 618625.6740273397],
 ['late 1900s', 506213.9935326726]]

As we have seen earlier, price and year_build is not highy corelated. It is being confirm here, as buildings that were build in early 1900s are generally more expensive than late 1900s.

## closer view of square foot living

In [31]:
#counting min,max,median and mean
mean=np.mean(house[:,3])
print("mean space is: "+str(mean))
median=np.median(house[:,3])
print("median space is: "+str(median))
print()
std=np.std(house[:,3])
print("space range of the houses are "+ str(np.min(house[:,3])) +" to "+ str(np.max(house[:,3])))

mean space is: 2080.3709483237635
median space is: 1910.0

space range of the houses are 370.0 to 13540.0


In [32]:
skew=(3*(mean-median))/std
print("Skewness is "+ str(skew))

Skewness is 0.5567206404185553


Since the skewness is positive, if we draw the distribution curve of "Square feet of living space" column, we will have Positive or right screw distribution. This means that, most of the outliers occur on the right side of the graph meaning <i>for bigger the area, we have more outliers.</i>

In [33]:
#correlation between living space and bedrooms
correlation44=np.corrcoef(house[:,3], house[:,1])
correlation44

array([[1.        , 0.57818024],
       [0.57818024, 1.        ]])

In [34]:
#correlation between living space and bathrooms
correlation44=np.corrcoef(house[:,3], house[:,2])
correlation44

array([[1.        , 0.75574115],
       [0.75574115, 1.        ]])

In [35]:
#correlation between living space and floor
correlation44=np.corrcoef(house[:,5], house[:,3])
correlation44

array([[1.        , 0.35402158],
       [0.35402158, 1.        ]])

In [36]:
#correlation between living space and zipcode
correlation44=np.corrcoef(house[:,3], house[:,14])
correlation44

array([[ 1.        , -0.19974884],
       [-0.19974884,  1.        ]])

In [37]:
#correlation between living space and number of view
correlation44=np.corrcoef(house[:,3], house[:,7])
correlation44

array([[1.        , 0.28470229],
       [0.28470229, 1.        ]])

In [24]:
#correlation between living space and water front
correlation44=np.corrcoef(house[:,3], house[:,6])
correlation44

array([[1.       , 0.1038529],
       [0.1038529, 1.       ]])

Square feet living space is highly correlated with the number of bedrooms and number of bathrooms, which is understandable as bigger houses tend to have more bedrooms and bathrooms. It is also foreseeable that, bigger houses are located away from the center which is also true for our dataset as square feet living and zip code are negatively correlated.


Square feet living is also corealted with the number of view and having waterfront or not. But, we cannot for sure say they are corelated, as number of view and waterfront depends on many other things, like location, negibourhood.

## how price changes with number of view

In [26]:
price=house[:,0]
view=house[:,7]

In [29]:
[[group_val, price[view==group_val].mean()] for group_val in np.unique(view)]


[[0.0, 496689.27749820275],
 [1.0, 812280.8373493976],
 [2.0, 792515.1456815817],
 [3.0, 971965.274509804],
 [4.0, 1463711.2382445142]]

As expected, house with more views are more expenssive but only difference is houses with 2 viwes. this kind of house is less expenssive than houses with 1 view.