In [1]:
import numpy as np

# 1 Linear algebra basic assignment:

  TODO: Solve the given problem and as well write down the markdown explaining the term and its equation in latex form.
  
  should incliude:
   -   what is 
   -   proprty of
   -   formula
      
  eg: Transpose of matrix: 
      - what is Transpose? 
      - formula for Transpose
      - Properties of Transpose
https://www.web-formulas.com/Math_Formulas/Linear_Algebra_Properties_of_Transposes.aspx

# 2 Define a symmertic 3x3 matric and print the transpose of the symmetric matrix

In linear algebra, a symmetric matrix is a square matrix that is equal to its transpose. https://blog.sopticek.net/2016/07/24/implementing-symmetric-matrix-in-python/

When top-right triangle and bottom left triangle of a matrix is same, it is called a symmetric matrix. In symmertic matrix, the main diagonal of the matrix is the axis of  symmetry. A symmetric matrix is always square and equal to its own transpose. 

The transpose of a matrix is a new matrix whose rows are the columns of the original. (This makes the columns of the new matrix the rows of the original). transpose of a matrix is denoted by, T, $M^T$. A defined matrix can be transposed, which creates a new matrix with the number of columnsand rows flipped. 

In [2]:
from numpy import array

In [3]:
M = array([[1, 2, 3],[1, 2, 1],[3, 2, 1]])
print(M)

[[1 2 3]
 [1 2 1]
 [3 2 1]]


In [4]:
M.T

array([[1, 1, 3],
       [2, 2, 2],
       [3, 1, 1]])

# 3 With the 3x3 matrix calculate the 
- lower traingular matrix
- upper triangular matrix

https://www.web-formulas.com/Math_Formulas/Linear_Algebra_Definition_of_Triangular_Matrices.aspx

A triangular matrix is a type of square matrix that has all values in the upper-right or lower-leftof the matrix with the remaining elements filled with zero values.  A triangular matrix with values only above the main diagonal is called an upper triangular matrix.  Whereas, a triangularmatrix with values only below the main diagonal is called a lower triangular matrix.  The inverse of a lower/upper triangular matrix is also lower/upper triangular matrix. But, The transpose of an upper/lower triangular matrix is lower/upper triangular matrix.

In [5]:
from numpy import array
from numpy import tril
from numpy import triu
M = array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
print(M)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [6]:
# lower triangular matrix
lower = tril(M)
lower

array([[1, 0, 0],
       [1, 2, 0],
       [1, 2, 3]])

In [7]:
# upper triangular matrix
upper = triu(M)
print(upper)

[[1 2 3]
 [0 2 3]
 [0 0 3]]


# 4 Define a 5x3 matrix and get the :
- diagonal vector
- get diagonal matrix form vector

A diagonal matrix is one where values outside of the main diagonal have a zero value, where themain diagonal is taken from the top left of the matrix to the bottom right. A diagonal matrix does not have to be square.  In the case of a rectangular matrix, thediagonal would cover the dimension with the smallest length. 
+ Transpose of the diagonal matrix D is as the same matrix, D = $D^T$. 
+ Under Multiplication, Diagonal Matrices are cumulative. I. e AB = BA

In [8]:
from numpy import diag
M = array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])
print(M)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [9]:
#diagonal vector
d = diag(M)
print(d)

[1 2 3]


In [10]:
#diagonal matrix from vector
D = diag(d)
print(D)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


#  5create a Identiy matrix

Identity Matrix is the matrix which is n × n square matrix where the diagonal consist of ones and the other elements are all zeros. It is also called as a Unit Matrix or Elementary matrix. An identity matrix is a square matrix that does not change a vector when multiplied. 
+ The identity matrix is always a square matrix
+ Multiplying any matrix by the identity results in the matrix itself
+ The product of two inverse matrices is always the identity

In [11]:
I=np.identity(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# 6 Define a orthogonal matrix and get:
- inverse of matrix
- show that
 $Q.Q^T=I$ 
 
 where Q is the orthogonal matrix

When the product of a matrix to its transpose gives identity value, then the matrix is said to be an orthogonal matrix. An orthogonal matrix is a square matrix whose rows are mutually orthonormal andwhose columns are mutually orthonormal.
+ This property of orthogonal is only applicable for the square matrix and orthogonal matrix is a symmetric matrix always.
+ The product of two orthogonal matrices is also an orthogonal matrix
+ The transpose of the orthogonal matrix is also orthogonal. Thus, if matrix A is orthogonal, then is $A^T$ is also an orthogonal matrix.
+ In the same way, the inverse of the orthogonal matrix which is $A^-1$ is also an orthogonal matrix.
+ The determinant of the orthogonal matrix has value $±1$.

<i>if the dot product of a matrix and its transpose is equal to an Identity matrix, then the matrix is a orthoginal matrix.</i>

In [12]:
from numpy.linalg import inv
#orthogonal matrix
Q = array([[1, 0],[0, -1]])
print(Q)

[[ 1  0]
 [ 0 -1]]


In [13]:
# inverse equivalence
V = inv(Q)
#print(Q.T)
print(V)

[[ 1.  0.]
 [-0. -1.]]


In [14]:
# identity equivalence
I = Q.dot(V)
print(I)

[[1. 0.]
 [0. 1.]]


# 7 Define a matrix and calulate the trace of matrix

Trace of a matrix
The trace of a square matrix is the sum of its diagonal elements.
https://www.statlect.com/matrix-algebra/trace-of-a-matrix

A trace of a square matrix is the sum of the values on the main diagonal of the matrix (top-leftto bottom-right).The trace is calculated as the sum of the diagonal values; for example, in the case of a 3×3matrix:
trace of matrix) =a1,1+a2,2+a3,3

In [15]:
M = array([[1, 2, 3],[1, 2, 3],[1, 2, 3]])             
# applying matrix.trace() method 
print(M)
trace = M.trace() 
    
print(trace)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
6


# 8 define a 3x3 matrix and calc determinant, ie not invertable

The determinant of a square matrix is a scalar representation of the volume of the matrix.
if the matrix is A= |(a b c), (d e f), (g h i)|. 
then determinant is
|A| = a(ei − fh) − b(di − fg) + c(dh − eg)


In [16]:
from numpy.linalg import det
# define matrix
A = array([[6, 4, 5],[4, 6, 6],[7, 5, 10]])
print(A)


[[ 6  4  5]
 [ 4  6  6]
 [ 7  5 10]]


In [17]:
# calculate determinant
B = det(A)
print(B)

78.0


# 9 create a 2x2 matrix , 1x3 matrix and calculate the rank of the matrix

The rank of a matrix is the estimate of the number of linearly independent rows or columns ina matrix.  An intuition for rank is to consider it the number of dimensions spanned by all of the vectorswithin a matrix.  For example, a rank of 0 suggest all vectors span a point, a rank of 1 suggestsall vectors span a line, a rank of 2 suggests all vectors span a two-dimensional plane.

In [18]:
from numpy.linalg import matrix_rank

In [19]:
A = array([[6, 4],[4, 6]])
print(A)
vr1 = matrix_rank(A)
print(vr1)

[[6 4]
 [4 6]]
2


In [20]:
v1 = array([1,2,3])
print(v1)
vr1 = matrix_rank(v1)
print(vr1)

[1 2 3]
1


# 10 create a 3*6 matrix with zeros and ones and count the zeros in matrix 
- also find the size of matrix
- calculate the matrix sparsity: count of zeros/size of matrix

A sparse matrix is a matrix that is comprised of mostly zero values.  Sparse matrices are distinctfrom matrices with mostly non-zero values, which are referred to as dense matrices. The sparsity of a matrix can be quantified with a score, which is the number of zero valuesin the matrix divided by the total number of elements in the matrix.

In [21]:
from numpy import count_nonzero
# create dense matrix
A = array([[1, 0, 0, 1, 0, 0],[0, 0, 2, 0, 0, 1],[0, 0, 0, 2, 0, 0]])
print(A)


[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [22]:
# calculate sparsity
sparsity = 1.0 - count_nonzero(A) / A.size
print(sparsity)

0.7222222222222222


# 11 convert the sparse using csr method and again reconstruct to dense
A = array([
    [1, 0, 0, 1, 0, 0],
    [0, 0, 2, 0, 0, 1],
    [0, 0, 0, 2, 0, 0]
]) #dense matrix

Compressed Sparse Row(CSR):  The sparse matrix is represented using three one-dimensionalarrays for the non-zero values, the extents of the rows, and the column indexes.

In [23]:
from scipy.sparse import csr_matrix
A = array ([[1, 0, 0, 1, 0, 0], [0, 0, 2, 0, 0, 1], [0, 0, 0, 2, 0, 0]])
print(A)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


In [24]:
# convert to sparse matrix (CSR method)
S = csr_matrix(A)
print(S)


  (0, 0)	1
  (0, 3)	1
  (1, 2)	2
  (1, 5)	1
  (2, 3)	2


In [25]:
# reconstruct dense matrix
B = S.todense()
print(B)

[[1 0 0 1 0 0]
 [0 0 2 0 0 1]
 [0 0 0 2 0 0]]


# 12 define a tensor of matrix of shape (3,3,3)

https://www.tensorflow.org/guide/tensor

A tensor is a generalization of vectors and matrices and is easily understood as a multidimensionalarray.In the general case, an array of numbers arranged on a regular grid with a variablenumber of axes is known as a tensor. A vector is a one-dimensional or first order tensor and a matrix is a two-dimensional or secondorder tensor.

In [26]:
T = array([[[1,2,3],   [4,5,6],   [7,8,9]],
           [[11,12,13], [14,15,16], [17,18,19]],
           [[21,22,23], [24,25,26], [27,28,29]]])
print(T.shape)
print(T)

(3, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


# 13 create a 2 tensor of size (3,3,3) and perform:
- tensor additon
- tensor substraction


The element-wise addition of two tensors with the same dimensions results in a new tensor withthe same dimensions where each scalar value is the element-wise addition of the scalars in theparent tensors.

In [27]:
A = array([[[1,2,3],   [4,5,6],   [7,8,9]],
           [[11,12,13], [14,15,16], [17,18,19]],
           [[21,22,23], [24,25,26], [27,28,29]]])
B = array([[[1,2,3],   [4,5,6],   [7,8,9]],
           [[11,12,13], [14,15,16], [17,18,19]],
           [[21,22,23], [24,25,26], [27,28,29]]])
C = A + B
print(C)

[[[ 2  4  6]
  [ 8 10 12]
  [14 16 18]]

 [[22 24 26]
  [28 30 32]
  [34 36 38]]

 [[42 44 46]
  [48 50 52]
  [54 56 58]]]


The element-wise subtraction of one tensor from another tensor with the same dimensionsresults in a new tensor with the same dimensions where each scalar value is the element-wisesubtraction of the scalars in the parent tensors.

In [28]:
C = A - B
print(C)

[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


# 14 perform a Hadamard Product for the above tensor

The element-wise multiplication of one tensor with another tensor with the same dimensionsresults in a new tensor with the same dimensions where each scalar value is the element-wisemultiplication of the scalars in the parent tensors.  As with matrices, the operation is referred toas the Hadamard Product.

In [29]:
C = A * B
print(C)

[[[  1   4   9]
  [ 16  25  36]
  [ 49  64  81]]

 [[121 144 169]
  [196 225 256]
  [289 324 361]]

 [[441 484 529]
  [576 625 676]
  [729 784 841]]]


# 15 Perform a Tensor division for a tensor of shape  T1 and T2 of shape(4,3,3) 

The element-wise division of one tensor with another tensor with the same dimensions results ina new tensor with the same dimensions where each scalar value is the element-wise division ofthe scalars in the parent tensors.

In [30]:
T = array([[[1,2,3],   [4,5,6],   [7,8,9]],
           [[11,12,13], [14,15,16], [17,18,19]],
           [[11,12,13], [14,15,16], [17,18,19]],
           [[21,22,23], [24,25,26], [27,28,29]]])
print(T.shape)
print(T)
B = array([[[1,2,3],   [4,5,6],   [7,8,9]],
           [[11,12,13], [14,15,16], [17,18,19]],
           [[11,12,13], [14,15,16], [17,18,19]],
           [[21,22,23], [24,25,26], [27,28,29]]])
print(B.shape)
print(B)

(4, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
(4, 3, 3)
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]


In [31]:
c= T/B
print(c)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


# 16 define a 2 tensor of 2x2 and calculate the tensor product

Given a tensor A with q dimensions and tensor B with r dimensions, the product of these tensors will be a new tensor with the order of q+ror, said another way,q+rdimensions.  The tensor product is not limited to tensors, but can also be performed on matricesand vectors.

In [32]:
from numpy import tensordot
A = array([[1,2],[3,4]])
B = array([[3,4],[1,2]])
print(A)
print()
print(B)

[[1 2]
 [3 4]]

[[3 4]
 [1 2]]


In [33]:
C = tensordot(A, B, axes=0)
print(C)

[[[[ 3  4]
   [ 1  2]]

  [[ 6  8]
   [ 2  4]]]


 [[[ 9 12]
   [ 3  6]]

  [[12 16]
   [ 4  8]]]]


# 17 calulate the factorization factors a matrix(Lu) decompostion for an array of shape 3x3
- recostruct the original matrix from the decompostion

The LU decomposition is for square matrices and decomposes a matrix into L and U components.
A=L·U.Where A is the square matrix that we wish to decompose,Lis the lower triangle matrixandUis the upper triangle matrix.A variation of this decompositionthat is numerically more stable to solve in practice is called the LUP decomposition, or the LUdecomposition with partial pivoting.
A=L·U·P.The rows of the parent matrix are re-ordered to simplify the decomposition process and theadditionalPmatrix specifies a way to permute the result or return the result to the originalorder.  There are also other variations of the LU. The LU decomposition is often used to simplifythe solving of systems of linear equations, such as finding the coefficients in a linear regression,as well as in calculating the determinant and inverse of a matrix

In [34]:
from scipy.linalg import lu
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(A)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [35]:
P, L, U = lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


In [36]:
B = P.dot(L).dot(U)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 18 from a matrix of shape 3x2
- calculate the QR decompostion
- reconstruct the original matrix

The QR decomposition is forn×mmatrices (not limited to square matrices) and decomposesa matrix intoQandRcomponents.A=Q·R. WhereAis the matrix that we wish to decompose,Qa matrix with the sizem×m, andRisan upper triangle matrix with the sizem×n.  The QR decomposition is found using an iterativenumerical method that can fail for those matrices that cannot be decomposed, or decomposedeasily.  Like the LU decomposition, the QR decomposition is often used to solve systems oflinear equations, although is not limited to square matrices.

In [37]:
from numpy.linalg import qr
A = array([[1, 2],
           [3, 4],
           [5, 6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [38]:
Q, R = qr(A,'complete')
print(Q)
print(R)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [39]:
# reconstruct
B = Q.dot(R)
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


# 19 define a 3x3 matrix calculate:
- cholesky decomposition using lower factorize
- reconstruct the original matrix

The Cholesky decomposition is for square symmetric matrices where all values are greater thanzero, so-called positive definite matrices.The decomposition is defined as follows:$A=L·L^T$.Where A is the matrix being decomposed,L is the lower triangular matrix and $L^T$ is thetranspose of L.  The decompose can also be written as the product of the upper triangular matrix, for example:$A=U^T·U$.Where U is the upper triangular matrix.  The Cholesky decomposition is used for solvinglinear least squares for linear regression, as well as simulation and optimization methods.  Whendecomposing symmetric matrices, the Cholesky decomposition is nearly twice as efficient as the LU decomposition and should be preferred in these cases.

In [40]:
from numpy.linalg import cholesky

In [41]:
A = array([[2, 1, 1],
           [1, 2, 1],
           [1, 1, 2]])
print(A)

[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [42]:
L = cholesky(A)
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [43]:
B = L.dot(L.T)
print(B)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]


# 20 define a 3x3 matrix and calculate the:
- eigendecomposition 


Eigendecomposition of a matrix is a type of decomposition that involves decomposing a squarematrix into a set of eigenvectors and eigenvalues.Eigenvectors are unit vectors, which means that their length or magnitude is equal to 1.0.  Theyare often referred as right vectors, which simply means a column vector (as opposed to a rowvector or a left vector).  A right-vector is a vector as we understand them.  Eigenvalues arecoefficients applied to eigenvectors that give the vectors their length or magnitude.  For example,a negative eigenvalue may reverse the direction of the eigenvector as part of scaling it.  A matrixthat has only positive eigenvalues is referred to as a positive definite matrix, whereas if theeigenvalues are all negative, it is referred to as a negative definite matrix.

In [44]:
from numpy.linalg import eig
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
values, vectors = eig(A)

In [46]:
print(values)
print()
print(vectors)

[ 1.61168440e+01 -1.11684397e+00 -9.75918483e-16]

[[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


https://machinelearningmastery.com/introduction-to-eigendecomposition-eigenvalues-and-eigenvectors/

# 21 from the above eigendecomposition conform an eigenvector and eigenvalue

We can confirm that a vector is indeed an eigenvector of a matrix.  We do this by multiplyingthe candidate eigenvector by the value vector and comparing the result with the eigenvalue.First, we will define a matrix, then calculate the eigenvalues and eigenvectors.  We will then testwhether the first vector and value are in fact an eigenvalue and eigenvector for the matrix. 

In [47]:
from numpy.linalg import eig
A = array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])

In [48]:
values, vectors = eig(A)


In [49]:
B = A.dot(vectors[:, 0])
print(B)
C = vectors[:, 0] * values[0]
print(C)

[ -3.73863537  -8.46653421 -13.19443305]
[ -3.73863537  -8.46653421 -13.19443305]


# 22 Reconstruct the matrix from the Eigendecompostion

We can reverse the process and reconstruct the original matrix given only the eigenvectors andeigenvalues.  First, the list of eigenvectors must be taken together as a matrix, where each vectorbecomes a row.  The eigenvalues need to be arranged into a diagonal matrix. 

In [50]:
from numpy.linalg import inv
from numpy import diag

In [51]:
Q = vectors
R = inv(Q)

In [52]:
L = diag(values)


In [53]:
B = Q.dot(L).dot(R)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# 23 calculate the L1 norm for a 1x3 matrix

The matrix norm ||A|| of a square matrix A is a nonnegative number associated with A having the properties that

1.
||A|| > 0 when A ≠ 0 and ||A|| = 0 if, and only if, A = 0;

2.
|| kA|| = | k | || A|| for any scalar k;

3.
|| A + B|| ≤ ||A|| + ||B||;

4.
|| AB|| ≤ || A|| || B||.

In [54]:
mat = np.array([[1, -1, 3]])
mat

array([[ 1, -1,  3]])

In [55]:
np.linalg.norm(mat, 1)

3.0

# 24calculate the L2 norm for the 1x4 matrix

In [56]:
mat = np.array([[1, -1, 3, 5]])
mat

array([[ 1, -1,  3,  5]])

In [57]:
np.linalg.norm(mat, 2)

6.0